import git
from github import Github

from src.core.config import GITHUB_TOKEN
from src.core.logger import get_logger

logger = get_logger("RepoMind.PR")


def _get_repo_name(repo_url: str) -> str:
    """Extract 'owner/repo' from a GitHub URL."""
    return repo_url.rstrip("/").split("github.com/")[-1].replace(".git", "")


def _get_default_branch(repo) -> str:
    try:
        return repo.default_branch
    except Exception:
        return "main"


def create_fix_pr(repo_url: str, local_repo_path: str, fix_summary: str) -> dict:
    """
    Commit the patched file to a new branch and open a GitHub PR.
    Returns {"success": True, "pr_url": "..."} or {"success": False, "error": "..."}
    """
    if not GITHUB_TOKEN:
        logger.error("GITHUB_TOKEN not set — skipping PR creation")
        return {"success": False, "error": "GITHUB_TOKEN not configured"}

    try:
        g = Github(GITHUB_TOKEN)
        repo_name = _get_repo_name(repo_url)
        remote_repo = g.get_repo(repo_name)
        default_branch = _get_default_branch(remote_repo)

        local_repo = git.Repo(local_repo_path)
        branch_name = "repomind-auto-fix"

        # Create branch if it doesn't exist; check out if it does
        existing_branches = [b.name for b in local_repo.branches]
        if branch_name in existing_branches:
            local_repo.git.checkout(branch_name)
            logger.info(f"Checked out existing branch: {branch_name}")
        else:
            local_repo.git.checkout("-b", branch_name)
            logger.info(f"Created new branch: {branch_name}")

        local_repo.git.add(A=True)

        # Only commit if there are staged changes
        if local_repo.is_dirty(index=True):
            local_repo.index.commit("🤖 RepoMind: Automated Bug Fix")
            logger.info("Committed changes")
        else:
            logger.info("No changes to commit — patch may already be up to date")

        origin = local_repo.remote(name="origin")
        # force=True only on the fix branch — never touches main/master
        origin.push(branch_name, force=True)
        logger.info("Pushed fix branch to remote")

        pr_body = f"""## 🤖 RepoMind Automated Fix

### 🧠 Summary
{fix_summary}

### ✅ Validation Steps
- Dependency-aware context collection
- AST syntax validation
- Sandboxed patch application
- Automated pytest execution
- Reflection-driven retry loop

### 🔧 Generated By
[RepoMind AI](https://github.com/k-satyam215/repomind-ai) — Autonomous Debugging Agent
"""

        # Check if a PR already exists for this branch
        existing_prs = list(remote_repo.get_pulls(
            state="open", head=f"{repo_name.split('/')[0]}:{branch_name}"
        ))

        if existing_prs:
            pr = existing_prs[0]
            pr.edit(body=pr_body)
            logger.info(f"Updated existing PR: {pr.html_url}")
        else:
            pr = remote_repo.create_pull(
                title="🤖 RepoMind: Automated Bug Fix",
                body=pr_body,
                head=branch_name,
                base=default_branch
            )
            logger.info(f"PR created: {pr.html_url}")

        return {"success": True, "pr_url": pr.html_url}

    except Exception as e:
        logger.error(f"PR creation failed: {e}")
        return {"success": False, "error": str(e)}
