import os
import git
from github import Github
from src.core.logger import get_logger

logger = get_logger("RepoMind.PR")


def _get_repo_name(repo_url: str):
    return repo_url.split("github.com/")[-1].replace(".git", "")


def _get_default_branch(repo):
    try:
        return repo.default_branch
    except Exception:
        return "main"


def create_fix_pr(repo_url: str, local_repo_path: str, fix_summary: str):

    token = os.getenv("GITHUB_TOKEN")

    if not token:
        logger.error("Missing GITHUB_TOKEN")
        return {"success": False, "error": "Missing token"}

    try:
        g = Github(token)
        repo_name = _get_repo_name(repo_url)
        repo = g.get_repo(repo_name)

        default_branch = _get_default_branch(repo)

        local_repo = git.Repo(local_repo_path)

        branch_name = "repomind-auto-fix"

        # create or checkout branch
        try:
            local_repo.git.checkout("-b", branch_name)
            logger.info("Created new branch for fix")
        except Exception:
            local_repo.git.checkout(branch_name)
            logger.info("Using existing fix branch")

        local_repo.git.add(A=True)

        commit_message = "🤖 RepoMind: Automated Bug Fix"
        local_repo.index.commit(commit_message)

        origin = local_repo.remote(name="origin")
        origin.push(branch_name, force=True)

        logger.info("Pushed fix branch to remote")

        pr_body = f"""
🤖 **RepoMind Automated Fix**

### 🧠 Summary
{fix_summary}

### ✅ Validation Steps
- Sandbox execution
- Automated test run
- Dependency-aware context reasoning
- Syntax validation

### 🔧 Generated By
RepoMind Autonomous Debugging Agent
"""

        pr = repo.create_pull(
            title="RepoMind Automated Fix",
            body=pr_body,
            head=branch_name,
            base=default_branch
        )

        logger.info(f"PR created successfully: {pr.html_url}")

        return {
            "success": True,
            "pr_url": pr.html_url
        }

    except Exception as e:
        logger.error(f"PR creation failed: {str(e)}")
        return {
            "success": False,
            "error": str(e)
        }